"""add sttep to leads

Revision ID: 484686d0a653
Revises: 200829a1feb1
Create Date: 2025-10-18 16:32:16.157761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484686d0a653'
down_revision: Union[str, Sequence[str], None] = '200829a1feb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('step', sa.Integer(), nullable=True))
    op.drop_column('leads', 'model_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('model_answer', sa.TEXT(), nullable=True))
    op.drop_column('leads', 'step')
    # ### end Alembic commands ###
