"""add last_token in lead

Revision ID: 6c7617a0f4ca
Revises: 48f655526434
Create Date: 2025-10-19 10:07:02.119611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7617a0f4ca'
down_revision: Union[str, Sequence[str], None] = '48f655526434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('last_token', sa.Text(), nullable=True))
    op.drop_column('leads', 'model_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('model_answer', sa.TEXT(), nullable=True))
    op.drop_column('leads', 'last_token')
    # ### end Alembic commands ###
