"""auth in lead

Revision ID: 08dcc0c773e5
Revises: 8768fe62d2f9
Create Date: 2025-10-18 21:53:51.802967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08dcc0c773e5'
down_revision: Union[str, Sequence[str], None] = '8768fe62d2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('login', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('password', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'is_admin')
    op.drop_column('leads', 'password')
    op.drop_column('leads', 'login')
    # ### end Alembic commands ###
