"""add offer to lead

Revision ID: 8768fe62d2f9
Revises: 2a75e3b7c387
Create Date: 2025-10-18 21:50:25.913367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8768fe62d2f9'
down_revision: Union[str, Sequence[str], None] = '2a75e3b7c387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('offer', sa.Text(), nullable=True))
    op.drop_column('leads', 'login')
    op.drop_column('leads', 'is_admin')
    op.drop_column('leads', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('password', sa.VARCHAR(), nullable=True))
    op.add_column('leads', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    op.add_column('leads', sa.Column('login', sa.VARCHAR(), nullable=True))
    op.drop_column('leads', 'offer')
    # ### end Alembic commands ###
