"""login unique

Revision ID: 48f655526434
Revises: 08dcc0c773e5
Create Date: 2025-10-18 21:55:06.494544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f655526434'
down_revision: Union[str, Sequence[str], None] = '08dcc0c773e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads') as batch_op:
        batch_op.create_unique_constraint('uq_leads_login', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads') as batch_op:
        batch_op.drop_constraint('uq_leads_login', type_='unique')
    # ### end Alembic commands ###
