"""create order table

Revision ID: 00cda237f1a7
Revises: 3fb01e4323b9
Create Date: 2025-10-28 21:49:03.285914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cda237f1a7'
down_revision: Union[str, Sequence[str], None] = '3fb01e4323b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('products', sa.Text(), nullable=True),
    sa.Column('sum', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment', sa.String(), nullable=True),
    sa.Column('delivery', sa.String(), nullable=True),
    sa.Column('track', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
