"""drop fields lead

Revision ID: 3fb01e4323b9
Revises: 6c7617a0f4ca
Create Date: 2025-10-22 19:17:56.794999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb01e4323b9'
down_revision: Union[str, Sequence[str], None] = '6c7617a0f4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'offer')
    op.drop_column('leads', 'model')
    op.drop_column('leads', 'step')
    op.drop_column('leads', 'last_token')
    op.drop_column('leads', 'needs')
    op.drop_column('leads', 'motive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('motive', sa.TEXT(), nullable=True))
    op.add_column('leads', sa.Column('needs', sa.TEXT(), nullable=True))
    op.add_column('leads', sa.Column('last_token', sa.TEXT(), nullable=True))
    op.add_column('leads', sa.Column('step', sa.INTEGER(), nullable=True))
    op.add_column('leads', sa.Column('model', sa.VARCHAR(), nullable=True))
    op.add_column('leads', sa.Column('offer', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
